"""Core data model: bills, per-currency balances and transactions.

See docs/data-model.md. Amounts are Decimal only (floats are rejected) and follow the
cardholder sign convention: positive = debt increases, negative = debt decreases.
"""

from __future__ import annotations

import hashlib
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

# strict=True: only real Decimal instances, so a float such as 28.25 can never sneak in.
Money = Annotated[Decimal, Field(strict=True)]
NonNegativeMoney = Annotated[Decimal, Field(strict=True, ge=0)]
Currency = Annotated[str, Field(pattern=r"^[A-Z]{3}$")]
Last4 = Annotated[str, Field(pattern=r"^\d{4}$")]

ZERO = Decimal("0")


class TxnType(StrEnum):
    PURCHASE = "purchase"  # 消费
    REFUND = "refund"  # 退款
    REPAYMENT = "repayment"  # 还款 (real money coming in)
    FEE = "fee"  # 手续费、年费
    INTEREST = "interest"  # 利息, including instalment interest
    CASH = "cash"  # 取现
    INSTALLMENT = "installment"  # 分期本金 due this period
    REBATE = "rebate"  # 返现
    FX_TRANSFER = "fx_transfer"  # 自动购汇 internal exchange: neither spending nor repayment
    ADJUSTMENT = "adjustment"  # 调整; unlisted adjustments become synthetic transactions


class _Model(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class Transaction(_Model):
    line_no: int = Field(ge=0)  # order within the bill; synthetic rows come last
    txn_id: str  # see make_txn_id()
    trans_date: date
    post_date: date | None = None
    txn_type: TxnType
    amount: Money  # settlement amount, cardholder sign convention
    currency: Currency  # settlement currency
    orig_amount: Money | None = None  # only when it differs from the settlement currency
    orig_currency: Currency | None = None
    fx_rate: Money | None = None  # e.g. "汇率:6.7648500"
    description_raw: str  # statement text after whitespace normalisation
    group_raw: str | None = None  # the bank's own group, e.g. ABC "消费/还款/分期/其他"
    merchant: str | None = None
    merchant_location: str | None = None
    card_last4: Last4 | None = None  # may be empty on FX and instalment rows
    installment: str | None = Field(default=None, pattern=r"^\d+/\d+$")  # "3/36"
    category: str | None = None
    synthetic: bool = False  # generated by reconciliation


class BillBalance(_Model):
    """Summary block of one currency account."""

    currency: Currency
    previous_balance: NonNegativeMoney  # 上期欠款
    previous_deposit: NonNegativeMoney = ZERO  # 上期溢缴款
    new_charges: Money  # 本期新增 (debits)
    interest_fees: Money = ZERO  # only when the bank lists them separately in the summary
    payments_credits: NonNegativeMoney  # 本期还款、退货 (credits)
    adjustments: Money = ZERO  # positive = debt increases
    amount_due: NonNegativeMoney  # 本期欠款
    deposit: NonNegativeMoney = ZERO  # 本期溢缴款
    min_payment: NonNegativeMoney | None = None


class Bill(_Model):
    """One statement of one account. A single e-mail may yield several (BOC combined bills)."""

    bank: str = Field(pattern=r"^[A-Z]+$")  # ABC / CCB / BOC
    account_id: str = Field(pattern=r"^[A-Z]+:(\d{4}|unknown)$")  # "ABC:0002", "CCB:unknown"
    cards: list[Last4]
    statement_date: date
    period_start: date | None = None
    period_end: date | None = None
    due_date: date | None = None  # may be empty when nothing is due; display only
    email_date: date  # decides which day's FX rate converts to CNY
    balances: list[BillBalance]
    transactions: list[Transaction]
    status: Literal["OK", "WARN", "UNVERIFIED"]
    warnings: list[str] = Field(default_factory=list)
    quality: int = 3  # later: 3 full, 2 partial, 1 heuristic; always 3 in the first version
    reported_at: datetime | None = None  # when the report e-mail was sent (stands in for outbox)
    source_message_id: str
    source_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    parser_name: str
    parser_version: int = Field(ge=1)


def make_txn_id(
    bank: str,
    account_id: str,
    trans_date: date,
    amount: Decimal,
    description: str,
    line_no: int,
) -> str:
    """Stable transaction id: the first 16 hex chars of a SHA-256 over the identifying fields.

    Amounts are normalised first, so Decimal("28.25") and Decimal("28.250") give the same id.
    """
    if not isinstance(amount, Decimal):
        raise TypeError(f"amount must be Decimal, got {type(amount).__name__}")
    normalized = format(amount.normalize(), "f")
    if normalized == "-0":
        normalized = "0"
    key = "\x1f".join(
        [bank, account_id, trans_date.isoformat(), normalized, description, str(line_no)]
    )
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]
